#!/bin/bash

export time_journal='journal.ldg'
export plot_dir='./plot'
export plot_data="$plot_dir/data.csv"

[[ ! -f "$time_journal" ]] && {
    touch "$time_journal";
    echo "Created new journal.";
}

acc_login_string(){
    echo "i $(date +'%Y/%m/%d %H:%M:%S') $*"
}

acc_logout_string() {
    if [[ -s $1 ]]; then
        echo "o $(date +'%Y/%m/%d %H:%M:%S') $*"
    else
        echo "o $(date +'%Y/%m/%d %H:%M:%S')"
    fi
}

acc_switch_string() {
    acc_logout_string
    acc_login_string "$*"
}

acc_login() {
    acc_login_string "$@" >> $time_journal
}

acc_logout() {
    acc_logout_string "$@" >> $time_journal
}

acc_switch() {
     acc_switch_string "$@" >> $time_journal
}

acc_login_interactive() {
    acc_login_string "$@" | vipe >> $time_journal
}

acc_logout_interactive() {
    acc_logout_string "$@" | vipe >> $time_journal
}

acc_switch_interactive() {
    acc_switch_string "$@" | vipe >> $time_journal
}

silent() {
    "$@" >& /dev/null
    return $?
}

check() {
    silent "$@" || {
        echo "checked execution failed: $*";
        exit 1;
    }
}

show() {
    period="today";
    [[ -s $1 ]] && {
        period="$1";
        shift
    }
    ledger bal -f $time_journal \
        -p "$period" \
        "$@";
}

fail() {
    echo "$@";
    exit 77;
}

change_pwd() {
    [[ -s $last_pwd ]] && {
        fail "Tried to change pwd twice. Need to reset_pwd.";
    }
    last_pwd="$(pwd)"
    export last_pwd
    check cd "$*"
}

reset_pwd() {
    [[ -z $last_pwd ]] && {
        fail "Tried to reset_pwd twice.";
    }
    check cd "$last_pwd"
    unset last_pwd
}

git_commit() {
    git add $time_journal
    check git diff --exit-code
    git commit -m "$(date +'%Y-%m-%d %H:%M:%S')"
    check git diff --exit-code
}

tran_diff() {
    git diff
    echo;
}

tran_start() {
    silent git diff --exit-code || {
        tran_diff
        fail "Failed to append to journal, there are pending changes! Abort or commit them first.";
    }
}

tran_check() {
    silent ledger -f "$time_journal" bal || {
        tran_diff
        fail "Transaction check failed. Run abort to abort or fix manually and run commit."
    }
}

tran_commit() {
   tran_check
   git_commit
}

tran_abort() {
    check git checkout -- "$time_journal"
    echo "Aborted.";
}

export_csv() {
    period="$1";
    style="collapse";
    [[ -n $2 ]] && style="$2";
    ledger -f journal.ldg bal \
           --no-total \
           --base \
           --balance-format='%a,%T\n' \
           "--$style" \
           -p "$1"
}

chart_pie() {
    export_csv "$@" > $plot_data
    change_pwd "$plot_dir"
    gnuplot pie.gp
    reset_pwd
}

check which ledger
check which gnuplot
check which sxiv

if [[ ! $1 ]]; then
    echo "Specify command."
    exit 1;
fi
command=$1
shift

case $command in
    "login"|"li")
        tran_start
        acc_login "$@";
        tran_commit
        show
        ;;
    "logout"|"lo")
        tran_start
        acc_logout "$@";
        tran_commit
        show
        ;;
    "switch"|"sw")
        tran_start
        acc_switch "$@";
        tran_commit
        show
        ;;
    "lii")
        tran_start
        acc_login_interactive "$@";
        tran_commit
        show
        ;;
    "loi")
        tran_start
        acc_logout_interactive "$@";
        tran_commit
        show
        ;;
    "swi")
        tran_start
        acc_switch_interactive "$@";
        tran_commit
        show
        ;;
    "abort")
        tran_abort
        ;;
    "commit")
        tran_commit
        ;;
    "tail")
        tail -n5 "$time_journal";
        ;;
    "show")
        show "$@"
        ;;
    "pie")
        chart_pie "$@"
        change_pwd "$plot_dir"
        sxiv pie.png
        reset_pwd
        ;;
    "cpie")
        while true; do
            chart_pie "$@"
            echo "updated ..."
            sleep 2;
        done
        ;;
    "check"|"chk")
        silent ledger -f "$time_journal" bal || echo "Journal corrupt.";
        silent git diff --exit-code || echo "Pending changes.";
        ;;
    *)
        echo "Wrong command.";
        exit 3;
esac
exit 0;
