#!/bin/bash

export time_journal='journal.ldg'
export plot_dir='./plot'
export plot_data="$plot_dir/data.csv"

[[ ! -f "$time_journal" ]] && {
    touch "$time_journal";
    echo "Created new journal.";
}

acc_login_string(){
    echo "i $(date +'%Y/%m/%d %H:%M:%S') $*"
}

acc_logout_string() {
    echo "o $(date +'%Y/%m/%d %H:%M:%S') $*"
}

acc_login() {
    acc_login_string "$@" | vipe >> $time_journal
}

acc_logout() {
    acc_logout_string "$@" | vipe >> $time_journal
}

acc_switch_string() {
    acc_logout_string "$1"
    acc_login_string "$2"
}

acc_switch() {
     acc_switch_string "$@" | vipe >> $time_journal
}

silent() {
    "$@" >& /dev/null
}

check() {
    silent "$@" || {
        echo "checked execution failed: $*";
        exit 1;
    }
}

show() {
    period="today";
    [[ -s $1 ]] && {
        period="$1";
    }
    ledger bal -f $time_journal -p "$period";
}

fail() {
    echo "$@";
    exit 77;
}

change_pwd() {
    [[ -s $last_pwd ]] && {
        fail "Tried to change pwd twice. Need to reset_pwd.";
    }
    last_pwd="$(pwd)"
    export last_pwd
    check cd "$*"
}

reset_pwd() {
    [[ -z $last_pwd ]] && {
        fail "Tried to reset_pwd twice.";
    }
    check cd "$last_pwd"
    unset last_pwd
}

export_csv() {
    ledger -f journal.ldg bal \
           --no-total \
           --base \
           --balance-format='%a,%T\n' \
           -p "$1"
}

chart_pie() {
    export_csv "$1" > $plot_data
    change_pwd "$plot_dir"
    gnuplot pie.gp
    reset_pwd
}

check which vipe
check which ledger
check which gnuplot
if [[ ! $1 ]]; then
    echo "Specify command."
    exit 1;
fi
command=$1
shift

case $command in
    "login"|"li")
        acc_login "$@";
        show
        ;;
    "logout"|"lo")
        acc_logout "$@";
        show
        ;;
    "switch"|"sw")
        acc_switch "$@";
        show
        ;;
    "show")
        show "$@"
        ;;
    "commit")
        git add $time_journal
        check git diff --exit-code
        git commit -m "$(date +'%Y/%m/%d %H:%M:%S') Automatic commit"
        ;;
    "pie")
        chart_pie "$@"
        change_pwd "$plot_dir"
        sxiv pie.png
        reset_pwd
        ;;
    "cpie")
        while true; do
            chart_pie "$@"
            echo "updated ..."
            sleep 2;
        done
        ;;
    default)
        echo "Wrong command.";
        exit 1;
esac
exit 0;
